#See https://nazarii.bardiuk.com/posts/hakyll-circle.html

version: 2

jobs:
  docker:
    - image: fpco/stack-build:lts
  steps:
    - checkout

    - restore_cache:
        name: Restore Cached Dependencies
        keys:
          # find a cache for the same stack.yaml
          - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          # when missing reuse from the same branch
          - stack-{{ .Branch }}-
          # when missing reuse the latest cache
          - stack-
    - run:
        name: Resolve/Update Dependencies
        command: stack setup
        command: stack build --dependencies-only
    - save_cache:
        name: Cache Dependencies
        key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
        paths:
          - ~/.stack
          - ./.stack-work

    - run:
        name: Build Site App
        command: stack build --pedantic
    - run:
        name: Generate Static Site
        command: stack exec site build

    - run:
        name: Publish GitHub Pages
        working_directory: './_site'
        command: |
          # initalize repo
          git init
          git config user.name  'CircleCI'
          git config user.email 'job@circleci.com'

          # add generated files
          git add .
          git commit -m "publish $CIRCLE_SHA1 [ci skip]"

          # push to pages branch
          git remote add origin "$CIRCLE_REPOSITORY_URL"
          git push --force origin master