name: Publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Install Nix
      uses: cachix/install-nix-action@v13

    - name: Setup Cachix
      uses: cachix/cachix-action@v9
      with:
        name: elderephemera
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Build
      run: |
        make site
        cp -r $(readlink result) site

    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        target_branch: site
        build_dir: site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
